let box = document.getElementById("container");
box.style.backgroundColor = "yellow";
box.style.margin = "20px";
box.style.padding = "10px";
box.style.fontSize = "18px";
box.style.height ="200px";
box.style.width="300px";
box.style.color ="blue";
box.style.fontWeight="600";